Nu3\Service\Product\Entity\Product:
  properties:
    properties:
      - Collection:
          fields:
            sku:
              - NotBlank: ~
              - Regex: '/^nu3_[1-9][0-9]{0,4}$/'
            status:
              - Choice:
                  choices: ["new", "approved", "not listed", "unavailable"]
                  groups: [approved]
            name:
              - NotBlank: ~
            type:
              - NotBlank: ~
              - Choice:
                  choices: ["config", "bundle", "book"]
            price:
              - Collection:
                  fields:
                    final:
                      - Type: integer
                      - Range:
                          min: 1
                          groups: [approved]
            tax_rate:
              - Range:
                  min: 0
                  max: 100
            attributes: ~
            seo:
              - Collection:
                  fields:
                    robots:
                      - Choice:
                          choices: ["noindex", "index", "nofollow", "follow"]
                          multiple: true
                    title:
                      - NotBlank: ~
                    description: ~

                  allowMissingFields: true
            manufacturer:
              - NotBlank: ~
            description:
              - NotBlank: { groups: [approved] }
            short_description: ~
            label_language:
              - Type: array

          allowMissingFields: true
