Nu3\Service\Product\Entity:
  properties:
    sku:
      - Type: string
      - NotBlank: ~
    properties:
      - Type: array
      - Collection:
          fields:
            name:
              - NotBlank: ~
            type:
              - Choice:
                  choices: [config, bundle, book, voucher]
            price:
              - Type: integer
              - GreaterThan:
                  value: 0
          allowExtraFields: true
          allowMissingFields: true