database:
  data_schema: catalog
  procedures_schema: catalog_sp
region:
  global: ['global']
  country: ['de', 'fr', 'at']
  language: ['de_de', 'fr_fr', 'at_de']
product:
  simple:
    validation_rules: simple.yml
  config:
    validation_rules: config.yml
  bundle:
    validation_rules: bundle.yml
shop:
  region_pairs:
    - ['de', 'de_de']
    - ['fr', 'fr_fr']
    - ['at', 'at_de']
    - ['at', 'de_de']
