database:
  username: user
  password: pass
  host: localhost
  database: default
  data_schema: catalog
  procedures_schema: catalog_sp
country:
  available: ['de']
language:
  available: ['de_de']
product:
  simple:
    validation_rules: simple.yml
  config:
    validation_rules: config.yml
  bundle:
    validation_rules: bundle.yml
