database:
  username: user
  password: pass
  host: localhost
  database: default
storage:
  available: ['catalog']
product:
  config:
    validation_rules: config.yml
  bundle:
    validation_rules: config.yml