database:
  username: user
  password: pass
  host: localhost
  database: default
storage:
  available: ['catalog', 'catalog_de', 'catalog_at']
product:
  config:
    validation_rules: config.yml
    default_values: config.php
  bundle:
    validation_rules: config.yml
    default_values: bundle.php