Nu3\Service\Product\Entity\Product:
  properties:
    attributes:
      -
        Collection:
          fields:
            sku:
              -
                NotBlank: null
              -
                Regex: '/^nu3_[1-9][0-9]{0,4}$/'
            status:
              -
                Choice:
                  choices:
                    - new
                    - approved
                    - 'not listed'
                    - unavailable
            name:
              -
                NotBlank: null
            type:
              -
                NotBlank: null
              -
                Choice:
                  choices:
                    - config
                    - bundle
                    - book
            final_price:
              -
                Type: integer
              -
                Range:
                  min: 1
                  groups:
                    - approved
            tax_rate:
              -
                Range:
                  min: 0
                  max: 100
            seo_robots:
              -
                Choice:
                  choices:
                    - noindex
                    - index
                    - nofollow
                    - follow
                  multiple: true
            seo_title:
              -
                NotBlank: null
            manufacturer:
              -
                NotBlank: null
            description:
              -
                NotBlank:
                  groups:
                    - approved
            short_description: null
            label_language:
              -
                Type: array
          allowMissingFields: true
          allowExtraFields: true
