INSERT INTO catalog (sku, properties) VALUES
('nu3_1', '{
    "variety": "config",
    "type": "book",
    "name": "silly_hodgkin",
    "manufacturer": "philips",
    "price": 5172,
    "tax_rate": 19,
    "seo_robots": ["noindex","follow"],
    "ingredient_list": 1,
    "label_language": ["en","it"],
    "attributes" : ["is_gluten_free","is_lactose_free"]                
}'),
('nu3_2', '{
    "variety": "config",
    "type": "book",
    "name": "dreamy_banach",
    "manufacturer": "microsoft",
    "price": 1936,
    "tax_rate": 19,
    "seo_robots": ["follow"],
    "ingredient_list": 1,
    "label_language": ["de","pl","sp","it","dk"],
    "attributes" : ["is_gluten_free","is_sugar_free","no_sugar_substitutes","only_natural_ingredients"]                
}'),
('nu3_3', '{
    "variety": "config",
    "type": "consumer",
    "name": "condescending_engelbart",
    "manufacturer": "adidas",
    "price": 7742,
    "tax_rate": 19,
    "seo_robots": ["nofollow"],
    "ingredient_list": 1,
    "label_language": ["pl","sp","en","it","dk","cn"],
    "attributes" : ["is_gelatine_free","is_sugar_free","no_artificial_flavours"]                
}'),
('nu3_4', '{
    "variety": "config",
    "type": "book",
    "name": "furious_kalam",
    "manufacturer": "microsoft",
    "price": 8733,
    "tax_rate": 19,
    "seo_robots": ["index","nofollow"],
    "ingredient_list": 1,
    "label_language": ["dk","cn"],
    "attributes" : ["is_gelatine_free","no_artificial_flavours","only_natural_ingredients"]                
}'),
('nu3_5', '{
    "variety": "config",
    "type": "consumer",
    "name": "lonely_haibt",
    "manufacturer": "microsoft",
    "price": 4637,
    "tax_rate": 19,
    "seo_robots": ["follow"],
    "ingredient_list": 1,
    "label_language": ["de","it"],
    "attributes" : ["is_gelatine_free"]                
}'),
('nu3_6', '{
    "variety": "config",
    "type": "book",
    "name": "loving_fermat",
    "manufacturer": "apple",
    "price": 3711,
    "tax_rate": 19,
    "seo_robots": ["index"],
    "ingredient_list": 1,
    "label_language": ["de","pl","it","dk"],
    "attributes" : ["no_sugar_substitutes"]                
}'),
('nu3_7', '{
    "variety": "config",
    "type": "voucher",
    "name": "sick_dijkstra",
    "manufacturer": "nu3",
    "price": 9125,
    "tax_rate": 19,
    "seo_robots": ["index","follow"],
    "ingredient_list": 1,
    "label_language": ["pl","sp","en","it","dk","cn"],
    "attributes" : ["is_vegetarian","is_gluten_free","no_artificial_flavours"]                
}'),
('nu3_8', '{
    "variety": "config",
    "type": "consumer",
    "name": "pedantic_hamilton",
    "manufacturer": "nu3",
    "price": 3347,
    "tax_rate": 19,
    "seo_robots": [],
    "ingredient_list": 1,
    "label_language": ["sp"],
    "attributes" : ["no_sugar_substitutes","only_natural_ingredients"]                
}'),
('nu3_9', '{
    "variety": "config",
    "type": "voucher",
    "name": "loving_fermi",
    "manufacturer": "philips",
    "price": 2722,
    "tax_rate": 19,
    "seo_robots": ["noindex"],
    "ingredient_list": 1,
    "label_language": ["pl","en","cn"],
    "attributes" : ["is_gelatine_free","no_sugar_substitutes","only_natural_ingredients"]                
}'),
('nu3_10', '{
    "variety": "config",
    "type": "book",
    "name": "pensive_roentgen",
    "manufacturer": "nu3",
    "price": 3317,
    "tax_rate": 19,
    "seo_robots": ["noindex","follow"],
    "ingredient_list": 1,
    "label_language": ["dk"],
    "attributes" : ["is_vegetarian","is_gluten_free","is_gelatine_free"]                
}'),
('nu3_11', '{
    "variety": "config",
    "type": "voucher",
    "name": "compassionate_kare",
    "manufacturer": "philips",
    "price": 4786,
    "tax_rate": 19,
    "seo_robots": ["noindex"],
    "ingredient_list": 1,
    "label_language": ["pl","en","it","dk","cn"],
    "attributes" : ["is_vegetarian","is_gluten_free","no_artificial_flavours"]                
}'),
('nu3_12', '{
    "variety": "config",
    "type": "book",
    "name": "clever_meninsky",
    "manufacturer": "philips",
    "price": 8247,
    "tax_rate": 19,
    "seo_robots": ["index","follow"],
    "ingredient_list": 1,
    "label_language": ["pl","sp","it","cn"],
    "attributes" : ["is_vegetarian","is_lactose_free","no_artificial_flavours"]                
}'),
('nu3_13', '{
    "variety": "config",
    "type": "book",
    "name": "infallible_hoover",
    "manufacturer": "philips",
    "price": 5727,
    "tax_rate": 19,
    "seo_robots": [],
    "ingredient_list": 1,
    "label_language": ["de","pl","sp","en","cn"],
    "attributes" : ["is_vegetarian"]                
}'),
('nu3_14', '{
    "variety": "config",
    "type": "consumer",
    "name": "awesome_lamarr",
    "manufacturer": "home24",
    "price": 5146,
    "tax_rate": 19,
    "seo_robots": ["noindex"],
    "ingredient_list": 1,
    "label_language": ["pl"],
    "attributes" : ["is_lactose_free"]                
}'),
('nu3_15', '{
    "variety": "config",
    "type": "consumer",
    "name": "hungry_kilby",
    "manufacturer": "home24",
    "price": 7924,
    "tax_rate": 19,
    "seo_robots": ["follow"],
    "ingredient_list": 1,
    "label_language": ["de","sp","en","it","dk","cn"],
    "attributes" : ["is_vegetarian","is_sugar_free","is_lactose_free","only_natural_ingredients"]                
}'),
('nu3_16', '{
    "variety": "config",
    "type": "consumer",
    "name": "backstabbing_mclean",
    "manufacturer": "adidas",
    "price": 1853,
    "tax_rate": 19,
    "seo_robots": [],
    "ingredient_list": 1,
    "label_language": ["de","pl","dk","cn"],
    "attributes" : ["is_gluten_free","is_gelatine_free"]                
}'),
('nu3_17', '{
    "variety": "config",
    "type": "book",
    "name": "tender_almeida",
    "manufacturer": "apple",
    "price": 5179,
    "tax_rate": 19,
    "seo_robots": ["follow"],
    "ingredient_list": 1,
    "label_language": ["de","pl","sp","en"],
    "attributes" : ["is_gelatine_free","is_sugar_free","no_artificial_flavours"]                
}'),
('nu3_18', '{
    "variety": "config",
    "type": "book",
    "name": "zen_goldberg",
    "manufacturer": "philips",
    "price": 4328,
    "tax_rate": 19,
    "seo_robots": ["follow"],
    "ingredient_list": 1,
    "label_language": ["sp"],
    "attributes" : ["is_sugar_free","is_lactose_free"]                
}'),
('nu3_19', '{
    "variety": "config",
    "type": "book",
    "name": "pedantic_feynman",
    "manufacturer": "microsoft",
    "price": 6159,
    "tax_rate": 19,
    "seo_robots": ["index"],
    "ingredient_list": 1,
    "label_language": ["de","pl","it","dk","cn"],
    "attributes" : ["is_vegetarian","is_lactose_free","no_artificial_flavours"]                
}'),
('nu3_20', '{
    "variety": "config",
    "type": "consumer",
    "name": "furious_cray",
    "manufacturer": "adidas",
    "price": 9220,
    "tax_rate": 19,
    "seo_robots": ["nofollow"],
    "ingredient_list": 1,
    "label_language": ["en"],
    "attributes" : ["is_vegetarian","is_gelatine_free"]                
}'),
('nu3_21', '{
    "variety": "config",
    "type": "consumer",
    "name": "big_shaw",
    "manufacturer": "microsoft",
    "price": 9438,
    "tax_rate": 19,
    "seo_robots": ["nofollow"],
    "ingredient_list": 1,
    "label_language": ["pl","sp"],
    "attributes" : ["is_vegetarian"]                
}'),

Notice: Undefined offset: 70 in /shared/src/ProductJSONGenerator/NameGenerator.php on line 243
('nu3_22', '{
    "variety": "config",
    "type": "book",
    "name": "_visvesvaraya",
    "manufacturer": "microsoft",
    "price": 4033,
    "tax_rate": 19,
    "seo_robots": ["index"],
    "ingredient_list": 1,
    "label_language": ["sp","dk"],
    "attributes" : ["is_gluten_free","is_sugar_free","is_lactose_free"]                
}'),
('nu3_23', '{
    "variety": "config",
    "type": "book",
    "name": "determined_shaw",
    "manufacturer": "adidas",
    "price": 5415,
    "tax_rate": 19,
    "seo_robots": ["index","follow"],
    "ingredient_list": 1,
    "label_language": ["pl","sp","en","it","dk","cn"],
    "attributes" : ["is_lactose_free"]                
}'),
('nu3_24', '{
    "variety": "config",
    "type": "book",
    "name": "evil_hawking",
    "manufacturer": "nike",
    "price": 997,
    "tax_rate": 19,
    "seo_robots": ["index","follow"],
    "ingredient_list": 1,
    "label_language": ["de","pl","it","cn"],
    "attributes" : ["is_gelatine_free","no_sugar_substitutes","no_artificial_flavours","only_natural_ingredients"]                
}'),
('nu3_25', '{
    "variety": "config",
    "type": "consumer",
    "name": "elated_kowalevski",
    "manufacturer": "apple",
    "price": 2654,
    "tax_rate": 19,
    "seo_robots": ["noindex"],
    "ingredient_list": 1,
    "label_language": ["de","pl","sp","it","cn"],
    "attributes" : ["is_gluten_free","is_sugar_free","no_sugar_substitutes","no_artificial_flavours"]                
}'),
('nu3_26', '{
    "variety": "config",
    "type": "voucher",
    "name": "small_archimedes",
    "manufacturer": "apple",
    "price": 1917,
    "tax_rate": 19,
    "seo_robots": ["index","follow"],
    "ingredient_list": 1,
    "label_language": ["sp","en","it","dk"],
    "attributes" : ["is_vegetarian","no_sugar_substitutes","is_lactose_free"]                
}'),
('nu3_27', '{
    "variety": "config",
    "type": "consumer",
    "name": "desperate_archimedes",
    "manufacturer": "adidas",
    "price": 2348,
    "tax_rate": 19,
    "seo_robots": ["nofollow"],
    "ingredient_list": 1,
    "label_language": ["sp","it"],
    "attributes" : ["is_gluten_free"]                
}'),
('nu3_28', '{
    "variety": "config",
    "type": "voucher",
    "name": "ecstatic_knuth",
    "manufacturer": "nike",
    "price": 9482,
    "tax_rate": 19,
    "seo_robots": ["noindex"],
    "ingredient_list": 1,
    "label_language": ["de"],
    "attributes" : ["is_lactose_free"]                
}'),
('nu3_29', '{
    "variety": "config",
    "type": "book",
    "name": "angry_aryabhata",
    "manufacturer": "microsoft",
    "price": 8448,
    "tax_rate": 19,
    "seo_robots": ["noindex"],
    "ingredient_list": 1,
    "label_language": ["pl","cn"],
    "attributes" : ["is_vegetarian","is_gluten_free","no_sugar_substitutes","is_lactose_free"]                
}'),
('nu3_30', '{
    "variety": "config",
    "type": "voucher",
    "name": "hungry_yonath",
    "manufacturer": "apple",
    "price": 5267,
    "tax_rate": 19,
    "seo_robots": ["index","nofollow"],
    "ingredient_list": 1,
    "label_language": ["de","sp","en","it","dk","cn"],
    "attributes" : ["is_lactose_free"]                
}'),
('nu3_31', '{
    "variety": "config",
    "type": "voucher",
    "name": "gloomy_brown",
    "manufacturer": "nike",
    "price": 1191,
    "tax_rate": 19,
    "seo_robots": [],
    "ingredient_list": 1,
    "label_language": ["pl","en","dk","cn"],
    "attributes" : ["is_vegetarian","is_gelatine_free","no_sugar_substitutes","no_artificial_flavours"]                
}'),
('nu3_32', '{
    "variety": "config",
    "type": "consumer",
    "name": "jovial_feynman",
    "manufacturer": "philips",
    "price": 4845,
    "tax_rate": 19,
    "seo_robots": [],
    "ingredient_list": 1,
    "label_language": ["de","pl","sp","it","dk","cn"],
    "attributes" : ["is_gelatine_free","only_natural_ingredients"]                
}'),
('nu3_33', '{
    "variety": "config",
    "type": "voucher",
    "name": "amazing_mcclintock",
    "manufacturer": "apple",
    "price": 132,
    "tax_rate": 19,
    "seo_robots": ["follow"],
    "ingredient_list": 1,
    "label_language": ["sp","cn"],
    "attributes" : ["is_vegetarian","is_gluten_free","no_sugar_substitutes","no_artificial_flavours"]                
}'),
('nu3_34', '{
    "variety": "config",
    "type": "book",
    "name": "loving_pike",
    "manufacturer": "nike",
    "price": 5521,
    "tax_rate": 19,
    "seo_robots": ["index","follow"],
    "ingredient_list": 1,
    "label_language": ["de","sp","en","it"],
    "attributes" : ["is_gluten_free","only_natural_ingredients"]                
}'),
('nu3_35', '{
    "variety": "config",
    "type": "voucher",
    "name": "cranky_kare",
    "manufacturer": "nu3",
    "price": 1070,
    "tax_rate": 19,
    "seo_robots": [],
    "ingredient_list": 1,
    "label_language": ["de","sp","dk","cn"],
    "attributes" : ["only_natural_ingredients"]                
}'),
('nu3_36', '{
    "variety": "config",
    "type": "voucher",
    "name": "elegant_wright",
    "manufacturer": "philips",
    "price": 2536,
    "tax_rate": 19,
    "seo_robots": ["follow"],
    "ingredient_list": 1,
    "label_language": ["sp","en","it","dk"],
    "attributes" : ["is_vegetarian","is_gelatine_free","is_lactose_free","only_natural_ingredients"]                
}'),
('nu3_37', '{
    "variety": "config",
    "type": "voucher",
    "name": "sad_beaver",
    "manufacturer": "nu3",
    "price": 4543,
    "tax_rate": 19,
    "seo_robots": [],
    "ingredient_list": 1,
    "label_language": ["de","pl","sp","en","cn"],
    "attributes" : ["is_vegetarian","no_sugar_substitutes"]                
}'),
('nu3_38', '{
    "variety": "config",
    "type": "book",
    "name": "hungry_shaw",
    "manufacturer": "nike",
    "price": 8420,
    "tax_rate": 19,
    "seo_robots": ["index","nofollow"],
    "ingredient_list": 1,
    "label_language": ["pl"],
    "attributes" : ["is_gluten_free","is_gelatine_free"]                
}'),
('nu3_39', '{
    "variety": "config",
    "type": "consumer",
    "name": "cocky_golick",
    "manufacturer": "adidas",
    "price": 1237,
    "tax_rate": 19,
    "seo_robots": ["index"],
    "ingredient_list": 1,
    "label_language": ["sp"],
    "attributes" : ["is_vegetarian","is_gluten_free","no_artificial_flavours"]                
}'),

Notice: Undefined offset: 154 in /shared/src/ProductJSONGenerator/NameGenerator.php on line 243
('nu3_40', '{
    "variety": "config",
    "type": "voucher",
    "name": "tender_",
    "manufacturer": "nu3",
    "price": 1090,
    "tax_rate": 19,
    "seo_robots": ["index"],
    "ingredient_list": 1,
    "label_language": ["de","pl","sp","it","cn"],
    "attributes" : ["no_artificial_flavours"]                
}'),
('nu3_41', '{
    "variety": "config",
    "type": "voucher",
    "name": "evil_ride",
    "manufacturer": "home24",
    "price": 6064,
    "tax_rate": 19,
    "seo_robots": [],
    "ingredient_list": 1,
    "label_language": ["dk"],
    "attributes" : ["no_sugar_substitutes"]                
}'),
('nu3_42', '{
    "variety": "config",
    "type": "voucher",
    "name": "clever_panini",
    "manufacturer": "adidas",
    "price": 236,
    "tax_rate": 19,
    "seo_robots": ["index"],
    "ingredient_list": 1,
    "label_language": ["sp","en","it","dk"],
    "attributes" : ["only_natural_ingredients"]                
}'),
('nu3_43', '{
    "variety": "config",
    "type": "consumer",
    "name": "ecstatic_lovelace",
    "manufacturer": "home24",
    "price": 7769,
    "tax_rate": 19,
    "seo_robots": ["nofollow"],
    "ingredient_list": 1,
    "label_language": ["en"],
    "attributes" : ["is_lactose_free"]                
}'),
('nu3_44', '{
    "variety": "config",
    "type": "consumer",
    "name": "reverent_brattain",
    "manufacturer": "home24",
    "price": 1562,
    "tax_rate": 19,
    "seo_robots": ["follow"],
    "ingredient_list": 1,
    "label_language": ["sp"],
    "attributes" : ["is_sugar_free","no_sugar_substitutes"]                
}'),
('nu3_45', '{
    "variety": "config",
    "type": "voucher",
    "name": "sharp_snyder",
    "manufacturer": "microsoft",
    "price": 4000,
    "tax_rate": 19,
    "seo_robots": ["follow"],
    "ingredient_list": 1,
    "label_language": ["pl","sp"],
    "attributes" : ["is_sugar_free"]                
}'),
('nu3_46', '{
    "variety": "config",
    "type": "consumer",
    "name": "peaceful_cori",
    "manufacturer": "microsoft",
    "price": 1079,
    "tax_rate": 19,
    "seo_robots": ["nofollow"],
    "ingredient_list": 1,
    "label_language": ["de","en","it","dk"],
    "attributes" : ["is_vegetarian","is_gluten_free","no_artificial_flavours"]                
}'),
('nu3_47', '{
    "variety": "config",
    "type": "consumer",
    "name": "nostalgic_shirley",
    "manufacturer": "nike",
    "price": 593,
    "tax_rate": 19,
    "seo_robots": ["index"],
    "ingredient_list": 1,
    "label_language": ["pl","sp","en","cn"],
    "attributes" : ["is_gluten_free","no_sugar_substitutes"]                
}'),
('nu3_48', '{
    "variety": "config",
    "type": "consumer",
    "name": "lonely_allen",
    "manufacturer": "home24",
    "price": 5960,
    "tax_rate": 19,
    "seo_robots": ["noindex"],
    "ingredient_list": 1,
    "label_language": ["pl","sp","en","it","dk"],
    "attributes" : ["is_gelatine_free","is_sugar_free","is_lactose_free"]                
}'),
('nu3_49', '{
    "variety": "config",
    "type": "voucher",
    "name": "goofy_sinoussi",
    "manufacturer": "nu3",
    "price": 4682,
    "tax_rate": 19,
    "seo_robots": ["follow"],
    "ingredient_list": 1,
    "label_language": ["de","sp","dk","cn"],
    "attributes" : ["is_gelatine_free","is_lactose_free","no_artificial_flavours","only_natural_ingredients"]                
}'),
('nu3_50', '{
    "variety": "config",
    "type": "consumer",
    "name": "suspicious_darwin",
    "manufacturer": "adidas",
    "price": 2761,
    "tax_rate": 19,
    "seo_robots": [],
    "ingredient_list": 1,
    "label_language": ["pl","sp","dk"],
    "attributes" : ["is_sugar_free","no_sugar_substitutes"]                
}'),
('nu3_51', '{
    "variety": "config",
    "type": "book",
    "name": "thirsty_meitner",
    "manufacturer": "philips",
    "price": 5365,
    "tax_rate": 19,
    "seo_robots": [],
    "ingredient_list": 1,
    "label_language": ["de","pl","sp","en","it","cn"],
    "attributes" : ["is_gluten_free","no_sugar_substitutes"]                
}'),
('nu3_52', '{
    "variety": "config",
    "type": "voucher",
    "name": "zen_khorana",
    "manufacturer": "microsoft",
    "price": 2848,
    "tax_rate": 19,
    "seo_robots": ["noindex"],
    "ingredient_list": 1,
    "label_language": ["de","pl","cn"],
    "attributes" : ["is_gelatine_free","is_sugar_free","no_artificial_flavours","only_natural_ingredients"]                
}'),
('nu3_53', '{
    "variety": "config",
    "type": "book",
    "name": "boring_kowalevski",
    "manufacturer": "adidas",
    "price": 4369,
    "tax_rate": 19,
    "seo_robots": ["nofollow"],
    "ingredient_list": 1,
    "label_language": ["de","sp","it","dk","cn"],
    "attributes" : ["is_vegetarian","is_gluten_free","is_sugar_free","only_natural_ingredients"]                
}'),
('nu3_54', '{
    "variety": "config",
    "type": "book",
    "name": "condescending_archimedes",
    "manufacturer": "nu3",
    "price": 7366,
    "tax_rate": 19,
    "seo_robots": ["nofollow"],
    "ingredient_list": 1,
    "label_language": ["de","sp","en","dk","cn"],
    "attributes" : ["is_vegetarian","is_sugar_free","no_artificial_flavours","only_natural_ingredients"]                
}'),

Notice: Undefined offset: 154 in /shared/src/ProductJSONGenerator/NameGenerator.php on line 243
('nu3_55', '{
    "variety": "config",
    "type": "book",
    "name": "compassionate_",
    "manufacturer": "apple",
    "price": 9623,
    "tax_rate": 19,
    "seo_robots": ["nofollow"],
    "ingredient_list": 1,
    "label_language": ["de","pl","sp","it","cn"],
    "attributes" : ["is_vegetarian","is_gluten_free","is_gelatine_free"]                
}'),
('nu3_56', '{
    "variety": "config",
    "type": "voucher",
    "name": "sad_noyce",
    "manufacturer": "philips",
    "price": 3965,
    "tax_rate": 19,
    "seo_robots": ["index","follow"],
    "ingredient_list": 1,
    "label_language": ["de","pl","sp","en","it","dk"],
    "attributes" : ["is_sugar_free","no_sugar_substitutes"]                
}'),
('nu3_57', '{
    "variety": "config",
    "type": "consumer",
    "name": "kickass_swirles",
    "manufacturer": "apple",
    "price": 3420,
    "tax_rate": 19,
    "seo_robots": ["index","follow"],
    "ingredient_list": 1,
    "label_language": ["de","sp","it","cn"],
    "attributes" : ["is_vegetarian","is_gelatine_free","is_sugar_free","only_natural_ingredients"]                
}'),
('nu3_58', '{
    "variety": "config",
    "type": "consumer",
    "name": "zen_jones",
    "manufacturer": "microsoft",
    "price": 3807,
    "tax_rate": 19,
    "seo_robots": ["index","nofollow"],
    "ingredient_list": 1,
    "label_language": ["de","sp","it","cn"],
    "attributes" : ["is_vegetarian","no_sugar_substitutes","no_artificial_flavours"]                
}'),
('nu3_59', '{
    "variety": "config",
    "type": "consumer",
    "name": "clever_leakey",
    "manufacturer": "apple",
    "price": 7937,
    "tax_rate": 19,
    "seo_robots": ["index","follow"],
    "ingredient_list": 1,
    "label_language": ["de","pl","sp","cn"],
    "attributes" : ["is_vegetarian","no_sugar_substitutes"]                
}'),
('nu3_60', '{
    "variety": "config",
    "type": "book",
    "name": "pensive_hoover",
    "manufacturer": "philips",
    "price": 6731,
    "tax_rate": 19,
    "seo_robots": ["nofollow"],
    "ingredient_list": 1,
    "label_language": ["pl","it","dk","cn"],
    "attributes" : ["is_gelatine_free","no_sugar_substitutes","only_natural_ingredients"]                
}'),
('nu3_61', '{
    "variety": "config",
    "type": "consumer",
    "name": "ecstatic_sinoussi",
    "manufacturer": "adidas",
    "price": 3697,
    "tax_rate": 19,
    "seo_robots": ["noindex"],
    "ingredient_list": 1,
    "label_language": ["de","sp","it","cn"],
    "attributes" : ["no_sugar_substitutes","is_lactose_free","no_artificial_flavours"]                
}'),
('nu3_62', '{
    "variety": "config",
    "type": "consumer",
    "name": "silly_edison",
    "manufacturer": "nu3",
    "price": 5145,
    "tax_rate": 19,
    "seo_robots": ["follow"],
    "ingredient_list": 1,
    "label_language": ["sp","en","it"],
    "attributes" : ["is_vegetarian","is_gelatine_free"]                
}'),
('nu3_63', '{
    "variety": "config",
    "type": "voucher",
    "name": "clever_swirles",
    "manufacturer": "nike",
    "price": 949,
    "tax_rate": 19,
    "seo_robots": ["noindex"],
    "ingredient_list": 1,
    "label_language": ["de","it","dk","cn"],
    "attributes" : ["is_gelatine_free","no_sugar_substitutes","is_lactose_free","no_artificial_flavours"]                
}'),
('nu3_64', '{
    "variety": "config",
    "type": "consumer",
    "name": "elastic_lalande",
    "manufacturer": "adidas",
    "price": 5974,
    "tax_rate": 19,
    "seo_robots": ["index","follow"],
    "ingredient_list": 1,
    "label_language": ["dk"],
    "attributes" : ["is_gluten_free","no_artificial_flavours"]                
}'),
('nu3_65', '{
    "variety": "config",
    "type": "book",
    "name": "grave_spence",
    "manufacturer": "nu3",
    "price": 4087,
    "tax_rate": 19,
    "seo_robots": [],
    "ingredient_list": 1,
    "label_language": ["de","pl","sp","en","dk","cn"],
    "attributes" : ["is_sugar_free","no_sugar_substitutes","is_lactose_free","no_artificial_flavours"]                
}'),
('nu3_66', '{
    "variety": "config",
    "type": "consumer",
    "name": "goofy_nightingale",
    "manufacturer": "microsoft",
    "price": 7756,
    "tax_rate": 19,
    "seo_robots": ["noindex"],
    "ingredient_list": 1,
    "label_language": ["de","pl","en","it","dk","cn"],
    "attributes" : ["is_vegetarian","is_gluten_free","no_artificial_flavours"]                
}'),
('nu3_67', '{
    "variety": "config",
    "type": "voucher",
    "name": "kickass_brahmagupta",
    "manufacturer": "nu3",
    "price": 5075,
    "tax_rate": 19,
    "seo_robots": ["noindex","follow"],
    "ingredient_list": 1,
    "label_language": ["sp"],
    "attributes" : ["is_gelatine_free","is_sugar_free","no_sugar_substitutes"]                
}'),
('nu3_68', '{
    "variety": "config",
    "type": "voucher",
    "name": "romantic_goodall",
    "manufacturer": "home24",
    "price": 4903,
    "tax_rate": 19,
    "seo_robots": ["noindex","follow"],
    "ingredient_list": 1,
    "label_language": ["de","cn"],
    "attributes" : ["is_vegetarian","is_gluten_free","is_lactose_free","no_artificial_flavours"]                
}'),
('nu3_69', '{
    "variety": "config",
    "type": "voucher",
    "name": "reverent_hugle",
    "manufacturer": "home24",
    "price": 6938,
    "tax_rate": 19,
    "seo_robots": [],
    "ingredient_list": 1,
    "label_language": ["sp"],
    "attributes" : ["is_vegetarian","is_sugar_free","no_sugar_substitutes","no_artificial_flavours"]                
}'),
('nu3_70', '{
    "variety": "config",
    "type": "book",
    "name": "sad_brattain",
    "manufacturer": "microsoft",
    "price": 7840,
    "tax_rate": 19,
    "seo_robots": ["index","nofollow"],
    "ingredient_list": 1,
    "label_language": ["it","cn"],
    "attributes" : ["is_gelatine_free","is_sugar_free","only_natural_ingredients"]                
}'),
('nu3_71', '{
    "variety": "config",
    "type": "consumer",
    "name": "desperate_bell",
    "manufacturer": "adidas",
    "price": 1127,
    "tax_rate": 19,
    "seo_robots": ["index","follow"],
    "ingredient_list": 1,
    "label_language": ["de","pl","sp","it","dk","cn"],
    "attributes" : ["no_sugar_substitutes","is_lactose_free"]                
}'),
('nu3_72', '{
    "variety": "config",
    "type": "consumer",
    "name": "grave_jang",
    "manufacturer": "apple",
    "price": 1850,
    "tax_rate": 19,
    "seo_robots": ["nofollow"],
    "ingredient_list": 1,
    "label_language": ["de","sp","en","it","dk","cn"],
    "attributes" : ["is_vegetarian","no_artificial_flavours"]                
}'),
('nu3_73', '{
    "variety": "config",
    "type": "consumer",
    "name": "reverent_pasteur",
    "manufacturer": "apple",
    "price": 8407,
    "tax_rate": 19,
    "seo_robots": ["nofollow"],
    "ingredient_list": 1,
    "label_language": ["pl","sp","it","dk"],
    "attributes" : ["is_gluten_free","only_natural_ingredients"]                
}'),
('nu3_74', '{
    "variety": "config",
    "type": "voucher",
    "name": "sick_shockley",
    "manufacturer": "nike",
    "price": 3214,
    "tax_rate": 19,
    "seo_robots": ["index","follow"],
    "ingredient_list": 1,
    "label_language": ["de","sp","it","dk","cn"],
    "attributes" : ["is_gluten_free","is_gelatine_free","only_natural_ingredients"]                
}'),
('nu3_75', '{
    "variety": "config",
    "type": "book",
    "name": "evil_bartik",
    "manufacturer": "adidas",
    "price": 7136,
    "tax_rate": 19,
    "seo_robots": ["noindex"],
    "ingredient_list": 1,
    "label_language": ["pl","sp","en","it","cn"],
    "attributes" : ["no_sugar_substitutes","no_artificial_flavours"]                
}'),
('nu3_76', '{
    "variety": "config",
    "type": "book",
    "name": "hungry_jennings",
    "manufacturer": "apple",
    "price": 5770,
    "tax_rate": 19,
    "seo_robots": ["noindex","follow"],
    "ingredient_list": 1,
    "label_language": ["de","pl","en","it","dk"],
    "attributes" : ["is_vegetarian","is_gelatine_free","is_sugar_free","only_natural_ingredients"]                
}'),
('nu3_77', '{
    "variety": "config",
    "type": "book",
    "name": "focused_turing",
    "manufacturer": "home24",
    "price": 3810,
    "tax_rate": 19,
    "seo_robots": [],
    "ingredient_list": 1,
    "label_language": ["de","pl","it","dk"],
    "attributes" : ["is_gelatine_free","is_sugar_free"]                
}'),
('nu3_78', '{
    "variety": "config",
    "type": "book",
    "name": "clever_varahamihira",
    "manufacturer": "philips",
    "price": 8687,
    "tax_rate": 19,
    "seo_robots": ["noindex"],
    "ingredient_list": 1,
    "label_language": ["de","pl","sp","en"],
    "attributes" : ["is_gelatine_free","is_sugar_free","no_artificial_flavours","only_natural_ingredients"]                
}'),
('nu3_79', '{
    "variety": "config",
    "type": "consumer",
    "name": "compassionate_cray",
    "manufacturer": "nike",
    "price": 3490,
    "tax_rate": 19,
    "seo_robots": ["noindex","follow"],
    "ingredient_list": 1,
    "label_language": ["de","dk","cn"],
    "attributes" : ["is_gluten_free","is_sugar_free","no_sugar_substitutes","only_natural_ingredients"]                
}'),
('nu3_80', '{
    "variety": "config",
    "type": "book",
    "name": "pensive_euclid",
    "manufacturer": "philips",
    "price": 565,
    "tax_rate": 19,
    "seo_robots": [],
    "ingredient_list": 1,
    "label_language": ["de","pl","sp","en","it","dk"],
    "attributes" : ["is_sugar_free","no_sugar_substitutes","no_artificial_flavours","only_natural_ingredients"]                
}'),
('nu3_81', '{
    "variety": "config",
    "type": "book",
    "name": "eager_heisenberg",
    "manufacturer": "home24",
    "price": 6455,
    "tax_rate": 19,
    "seo_robots": [],
    "ingredient_list": 1,
    "label_language": ["de","sp","en","it","dk"],
    "attributes" : ["is_gluten_free","is_sugar_free","no_sugar_substitutes","no_artificial_flavours"]                
}'),
('nu3_82', '{
    "variety": "config",
    "type": "consumer",
    "name": "lonely_bartik",
    "manufacturer": "adidas",
    "price": 9622,
    "tax_rate": 19,
    "seo_robots": ["index"],
    "ingredient_list": 1,
    "label_language": ["pl","sp","en","dk","cn"],
    "attributes" : ["is_gluten_free","is_lactose_free"]                
}'),
('nu3_83', '{
    "variety": "config",
    "type": "consumer",
    "name": "sharp_bose",
    "manufacturer": "microsoft",
    "price": 4202,
    "tax_rate": 19,
    "seo_robots": ["noindex","nofollow"],
    "ingredient_list": 1,
    "label_language": ["cn"],
    "attributes" : ["is_vegetarian"]                
}'),
('nu3_84', '{
    "variety": "config",
    "type": "voucher",
    "name": "high_shannon",
    "manufacturer": "nike",
    "price": 6101,
    "tax_rate": 19,
    "seo_robots": ["noindex","follow"],
    "ingredient_list": 1,
    "label_language": ["pl","cn"],
    "attributes" : ["is_vegetarian","is_gluten_free","is_sugar_free","no_artificial_flavours"]                
}'),
('nu3_85', '{
    "variety": "config",
    "type": "voucher",
    "name": "fervent_heyrovsky",
    "manufacturer": "philips",
    "price": 704,
    "tax_rate": 19,
    "seo_robots": ["follow"],
    "ingredient_list": 1,
    "label_language": ["pl","sp","en","it","dk"],
    "attributes" : ["is_sugar_free","no_artificial_flavours","only_natural_ingredients"]                
}'),
('nu3_86', '{
    "variety": "config",
    "type": "book",
    "name": "hungry_kare",
    "manufacturer": "adidas",
    "price": 8524,
    "tax_rate": 19,
    "seo_robots": ["noindex","follow"],
    "ingredient_list": 1,
    "label_language": ["pl","it","dk","cn"],
    "attributes" : ["is_vegetarian","is_gluten_free","no_sugar_substitutes","is_lactose_free"]                
}'),
('nu3_87', '{
    "variety": "config",
    "type": "consumer",
    "name": "sleepy_poitras",
    "manufacturer": "home24",
    "price": 245,
    "tax_rate": 19,
    "seo_robots": ["noindex"],
    "ingredient_list": 1,
    "label_language": ["de","pl","sp","en","it"],
    "attributes" : ["is_vegetarian"]                
}'),
('nu3_88', '{
    "variety": "config",
    "type": "consumer",
    "name": "tiny_meninsky",
    "manufacturer": "microsoft",
    "price": 1853,
    "tax_rate": 19,
    "seo_robots": ["index","nofollow"],
    "ingredient_list": 1,
    "label_language": ["de","pl","sp","en","dk"],
    "attributes" : ["no_sugar_substitutes"]                
}'),
('nu3_89', '{
    "variety": "config",
    "type": "consumer",
    "name": "sad_brahmagupta",
    "manufacturer": "adidas",
    "price": 2822,
    "tax_rate": 19,
    "seo_robots": ["follow"],
    "ingredient_list": 1,
    "label_language": ["sp"],
    "attributes" : ["no_sugar_substitutes","is_lactose_free","only_natural_ingredients"]                
}'),
('nu3_90', '{
    "variety": "config",
    "type": "voucher",
    "name": "peaceful_bell",
    "manufacturer": "microsoft",
    "price": 2915,
    "tax_rate": 19,
    "seo_robots": [],
    "ingredient_list": 1,
    "label_language": ["de","pl","sp","en","it","cn"],
    "attributes" : ["is_gelatine_free","no_sugar_substitutes","is_lactose_free"]                
}'),
('nu3_91', '{
    "variety": "config",
    "type": "book",
    "name": "admiring_jennings",
    "manufacturer": "nu3",
    "price": 8823,
    "tax_rate": 19,
    "seo_robots": [],
    "ingredient_list": 1,
    "label_language": ["de","pl","sp","en","dk","cn"],
    "attributes" : ["is_gluten_free","is_gelatine_free","is_sugar_free","is_lactose_free"]                
}'),
('nu3_92', '{
    "variety": "config",
    "type": "consumer",
    "name": "tender_poitras",
    "manufacturer": "philips",
    "price": 2057,
    "tax_rate": 19,
    "seo_robots": ["index","nofollow"],
    "ingredient_list": 1,
    "label_language": ["sp","dk","cn"],
    "attributes" : ["is_vegetarian","no_sugar_substitutes"]                
}'),
('nu3_93', '{
    "variety": "config",
    "type": "voucher",
    "name": "romantic_fermi",
    "manufacturer": "nike",
    "price": 5123,
    "tax_rate": 19,
    "seo_robots": ["index"],
    "ingredient_list": 1,
    "label_language": ["de","sp","en","it","dk","cn"],
    "attributes" : ["is_sugar_free","is_lactose_free"]                
}'),
('nu3_94', '{
    "variety": "config",
    "type": "consumer",
    "name": "infallible_curie",
    "manufacturer": "home24",
    "price": 7538,
    "tax_rate": 19,
    "seo_robots": [],
    "ingredient_list": 1,
    "label_language": ["it"],
    "attributes" : ["is_gluten_free","is_gelatine_free","no_artificial_flavours","only_natural_ingredients"]                
}'),
('nu3_95', '{
    "variety": "config",
    "type": "voucher",
    "name": "pensive_sammet",
    "manufacturer": "apple",
    "price": 7509,
    "tax_rate": 19,
    "seo_robots": ["noindex"],
    "ingredient_list": 1,
    "label_language": ["sp","en"],
    "attributes" : ["no_sugar_substitutes"]                
}'),
('nu3_96', '{
    "variety": "config",
    "type": "book",
    "name": "sick_tesla",
    "manufacturer": "microsoft",
    "price": 3133,
    "tax_rate": 19,
    "seo_robots": ["noindex","follow"],
    "ingredient_list": 1,
    "label_language": ["dk"],
    "attributes" : ["is_gluten_free","no_sugar_substitutes","is_lactose_free"]                
}'),
('nu3_97', '{
    "variety": "config",
    "type": "book",
    "name": "high_cray",
    "manufacturer": "apple",
    "price": 5065,
    "tax_rate": 19,
    "seo_robots": ["index"],
    "ingredient_list": 1,
    "label_language": ["pl","en","cn"],
    "attributes" : ["no_sugar_substitutes","is_lactose_free"]                
}'),
('nu3_98', '{
    "variety": "config",
    "type": "voucher",
    "name": "angry_elion",
    "manufacturer": "philips",
    "price": 7780,
    "tax_rate": 19,
    "seo_robots": ["index","follow"],
    "ingredient_list": 1,
    "label_language": ["de","pl","sp","en","dk","cn"],
    "attributes" : ["only_natural_ingredients"]                
}'),
('nu3_99', '{
    "variety": "config",
    "type": "consumer",
    "name": "affectionate_mccarthy",
    "manufacturer": "adidas",
    "price": 4522,
    "tax_rate": 19,
    "seo_robots": ["index"],
    "ingredient_list": 1,
    "label_language": ["cn"],
    "attributes" : ["is_sugar_free"]                
}'),
('nu3_100', '{
    "variety": "config",
    "type": "book",
    "name": "sleepy_hugle",
    "manufacturer": "apple",
    "price": 8325,
    "tax_rate": 19,
    "seo_robots": ["noindex"],
    "ingredient_list": 1,
    "label_language": ["en","it","cn"],
    "attributes" : ["only_natural_ingredients"]                
}'),
('nu3_101', '{
    "variety": "config",
    "type": "consumer",
    "name": "sleepy_ride",
    "manufacturer": "nike",
    "price": 7285,
    "tax_rate": 19,
    "seo_robots": ["noindex","follow"],
    "ingredient_list": 1,
    "label_language": ["de","pl","sp","en","it","cn"],
    "attributes" : ["is_vegetarian","is_gelatine_free","no_sugar_substitutes","is_lactose_free"]                
}');
