Nu3\Service\Product\Entity\Product:
  properties:
    sku:
      - NotBlank: ~
      - Regex: '/^nu3_[1-9][0-9]*$/'
    type:
      - NotBlank: ~
      - Choice:
          choices: ["config", "bundle", "config"]
    properties:
      - All:
        - Collection:
            fields:
              status:
                - Choice:
                    choices: ["new", "approved", "not listed", "unavailable"]
              name:
                - NotBlank: ~
              final_gross_price:
                - Optional:
                  - Type: integer
                  - Range:
                      min: 1
                      groups: [sellable]
              tax_rate:
                - Optional:
                  - Range:
                      min: 0
                      max: 100
              seo_robots:
                - Optional:
                  - Choice:
                      choices: ["noindex", "index", "nofollow", "follow"]
                      multiple: true
              seo_title:
                - Optional:
                  - NotBlank: ~
              manufacturer:
                - Optional:
                  - NotBlank: ~
              description:
                - Optional:
                  - NotBlank: { groups: [sellable] }
              short_description:
                - Optional: ~
              label_language:
                - Optional:
                  - Type: array
            allowMissingFields: false
            allowExtraFields: true
