Nu3\Service\Product\Entity\Product:
  properties:
    properties:
      - All:
        - Collection:
            fields:
              final_gross_price:
                - Required: null
              children:
                - NotBlank: ~
                - Type: array
